{{- if .Values.metabase.enabled }}
{{- $fullName := include "app.fullname" . -}}
{{- $metabase := .Values.metabase | default dict -}}
{{- $metabaseIngress := get $metabase "ingress" | default dict -}}
{{- $metabaseHost := get $metabaseIngress "host" | default (printf "ccq-dashboard-%s.cloud-platform.service.justice.gov.uk" .Values.environment) -}}
{{- $metabaseAnnotations := merge (dict) (.Values.ingress.annotations | default dict) (get $metabaseIngress "annotations" | default dict) -}}
{{- $metabaseIngressAllowedIpRanges := get $metabaseIngress "allowed_ip_ranges" | default (list) -}}
{{- if gt (len $metabaseIngressAllowedIpRanges) 0 -}}
{{- $metabaseAnnotations = merge $metabaseAnnotations (dict "nginx.ingress.kubernetes.io/whitelist-source-range" (join "," $metabaseIngressAllowedIpRanges)) -}}
{{- end -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ $fullName }}-metabase
  labels:
    app: {{ template "app.name" . }}
    chart: {{ template "app.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
{{- with $metabaseAnnotations }}
  annotations:
{{ toYaml . | indent 4 }}
{{- end }}
spec:
  ingressClassName: default
  tls:
    - hosts:
        - '{{ $metabaseHost }}'
  rules:
    - host: '{{ $metabaseHost }}'
      http:
        paths:
          - path: "/"
            pathType: ImplementationSpecific
            backend:
              service:
                name: {{ $fullName }}-metabase
                port:
                  number: 80
{{- end }}