include:
  - docker-compose.embedded.yml
  - docker-compose.standalone.yml

services:
  # embedded dependencies
  #
  # separated so that other services can include
  # docker-compose.embedded.yml without nginx/host stub
  nginx:
    container_name: ccq-embedded-nginx
    image: nginxinc/nginx-unprivileged:alpine
    ports:
      - 8080:8080
    volumes:
      - ./docker/compose/nginx/default.conf.template:/etc/nginx/templates/default.conf.template:ro
      - ./docker/compose/nginx/docker-upstream.conf.template:/etc/nginx/templates/zz-docker-upstream.conf.template:ro
      - ./docker/compose/nginx/proxy.conf:/etc/nginx/proxy.conf:ro
      - ./docker/compose/nginx/maps.conf:/etc/nginx/maps.conf:ro
    depends_on:
      - ccq-embedded
    environment:
      NGINX_UPSTREAM_CCQ: ccq_upstream
      NGINX_UPSTREAM_CCQ_SERVER: ccq-embedded:3000

  host-service-stub:
    container_name: ccq-host-service-stub
    image: wiremock/wiremock:3.13.1
    volumes:
      - ./docker/compose/host-service-stub/mappings:/home/wiremock/mappings:ro
    command:
      - --global-response-templating
