apiVersion: v1
appVersion: "1.0"
description: A Helm chart for Kubernetes
name: laa-check-client-qualifies
version: 0.2.0
dependencies:
  - name: postgresql
    version: ^11.0.0
    condition: postgresql.enabled
    repository: https://charts.bitnami.com/bitnami
