apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ .Release.Name | trunc 26 }}-metrics
  labels:
    app: {{ template "app.name" . }}
    chart: {{ template "app.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  schedule: '7 0 * * *'
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 0
  failedJobsHistoryLimit: 0
  jobTemplate:
    spec:
      backoffLimit: 1
      template:
        spec:
          containers:
          - name: metrics
            image: '{{ .Values.image.repository }}:{{ .Values.image.tag }}'
            imagePullPolicy: IfNotPresent
            command: ['rake', "job:metrics:generate"]
{{ include "app.envs" . | nindent 12 }}
            resources:
              limits:
                cpu: 200m
                memory: 256Mi
              requests:
                cpu: 100m
                memory: 128Mi
          restartPolicy: Never
