{{- $fullName := include "app.fullname" . -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ $fullName }}
  labels:
    app: {{ template "app.name" . }}
    chart: {{ template "app.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
{{- with .Values.ingress.annotations }}
  annotations:
{{ toYaml . | indent 4 }}
{{- end }}
spec:
  ingressClassName: default
  tls:
  {{- range .Values.ingress.hosts }}
    - hosts:
        - '{{- .host }}'
    {{- if .secret }}
      secretName: '{{- .secret }}'
    {{- end }}
  {{- end }}
  {{- if .Values.metabase.enabled }}
    - hosts:
      - "ccq-dashboard-{{ .Values.cfe.environment_name }}.cloud-platform.service.justice.gov.uk"
  {{- end }}
  rules:
  {{- range .Values.ingress.hosts }}
    - host: '{{- .host }}'
      http:
        paths:
          - path: /
            pathType: ImplementationSpecific
            backend:
              service:
                name: {{ $fullName }}
                port:
                  name: http
  {{- end }}
    {{- if .Values.metabase.enabled }}
    - host: "ccq-dashboard-{{ .Values.cfe.environment_name }}.cloud-platform.service.justice.gov.uk"
      http:
        paths:
          - path: "/"
            pathType: ImplementationSpecific
            backend:
              service:
                name: {{ $fullName }}-metabase-service
                port:
                  number: 80
    {{- end }}

