# A list of valid entries on the `event_type` field for the AnalyticsEvent table, called by the AnalyticsService class
# New `event_type` fields will need to be added here to prevent AnalyticsService from throwing an error
allowed_event_types:
- certificated_level_of_help_chosen
- click_controlled_work_form
- click_laa_cw_forms
- click_lc_guidance_certificated
- click_lc_guidance_certificated_additional_properties_guidance
- click_lc_guidance_certificated_assets
- click_lc_guidance_certificated_bankruptcy
- click_lc_guidance_certificated_business_capital
- click_lc_guidance_certificated_capital
- click_lc_guidance_certificated_children
- click_lc_guidance_certificated_dependants_allowance
- click_lc_guidance_certificated_disregarded_payments
- click_lc_guidance_certificated_domestic_abuse
- click_lc_guidance_certificated_equity_disregard_for_domestic_abuse
- click_lc_guidance_certificated_housing_costs
- click_lc_guidance_certificated_income
- click_lc_guidance_certificated_lc_guidance_certificated
- click_lc_guidance_certificated_mandatory_discretionary_disregarded_benefits
- click_lc_guidance_certificated_mandatory_discretionary_disregarded_capital
- click_lc_guidance_certificated_outgoings
- click_lc_guidance_certificated_over_60
- click_lc_guidance_certificated_passporting_benefit
- click_lc_guidance_certificated_police
- click_lc_guidance_certificated_principles_for_exercising_discretion_assets
- click_lc_guidance_certificated_principles_for_exercising_discretion_income
- click_lc_guidance_certificated_prisoner
- click_lc_guidance_certificated_properties_guidance
- click_lc_guidance_certificated_self_employed
- click_lc_guidance_certificated_smod
- click_lc_guidance_certificated_trusts
- click_lc_guidance_certificated_under_18
- click_lc_guidance_certificated_upper_tribunal
- click_lc_guidance_certificated_vehicle
- click_lc_guidance_controlled
- click_lc_guidance_controlled_additional_properties_guidance
- click_lc_guidance_controlled_assets
- click_lc_guidance_controlled_asylum_support
- click_lc_guidance_controlled_child_assets
- click_lc_guidance_controlled_child_income
- click_lc_guidance_controlled_children
- click_lc_guidance_controlled_dependants_allowance
- click_lc_guidance_controlled_disregarded_payments
- click_lc_guidance_controlled_equity_disregard_for_domestic_abuse
- click_lc_guidance_controlled_evidence
- click_lc_guidance_controlled_housing_costs
- click_lc_guidance_controlled_income
- click_lc_guidance_controlled_lc_guidance_controlled
- click_lc_guidance_controlled_legacy_guidance
- click_lc_guidance_controlled_mandatory_discretionary_disregarded_benefits
- click_lc_guidance_controlled_mandatory_discretionary_disregarded_capital
- click_lc_guidance_controlled_means_aggregation
- click_lc_guidance_controlled_outgoings
- click_lc_guidance_controlled_over_60
- click_lc_guidance_controlled_passporting_benefit
- click_lc_guidance_controlled_principles_for_exercising_discretion_assets
- click_lc_guidance_controlled_principles_for_exercising_discretion_income
- click_lc_guidance_controlled_properties_guidance
- click_lc_guidance_controlled_self_employed
- click_lc_guidance_controlled_smod
- click_lc_guidance_controlled_under_18
- click_legal_aid_checker_for_public
- click_legal_aid_learning
- click_legislation_ammendments
- click_legislation_cla_2012
- click_legislation_CLAR_2013
- click_legislation_CLAR_2013_childcare
- click_legislation_CLAR_2013_housing
- click_legislation_CLAR_2013_individual_resources
- click_legislation_LASPO_2012_immigration
- click_means_testing_guidance
- click_mental_health_guidance
- controlled_level_of_help_chosen
- page_view
- referral
- validation_message