# config/allowed_analytics_pages.yml
# A list of valid entries for the page field on the analytics service
# New pages will need to be added here to prevent AnalyticsService from throwing an error
allowed_pages:
  - add_benefits
  - additional_property
  - additional_property_details
  - aggregated_means
  - applicant
  - assets
  - asylum_support
  - benefit_details
  - benefits
  - change_answers_show
  - change_answers_update
  - check_additional_property
  - check_additional_property_details
  - check_aggregated_means
  - check_answers
  - check_applicant
  - check_assets
  - check_asylum_support
  - check_benefit_details
  - check_benefits
  - check_client_age
  - check_dependant_details
  - check_dependant_income
  - check_dependant_income_details
  - check_domestic_abuse_applicant
  - check_employment
  - check_employment_status
  - check_housing_benefit
  - check_housing_benefit_details
  - check_housing_costs
  - check_how_to_aggregate
  - check_immigration_or_asylum
  - check_immigration_or_asylum_type
  - check_immigration_or_asylum_type_upper_tribunal
  - check_income
  - check_level_of_help
  - check_matter_type
  - check_mortgage_or_loan_payment
  - check_new_benefits
  - check_other_income
  - check_outgoings
  - check_partner_additional_property
  - check_partner_additional_property_details
  - check_partner_assets
  - check_partner_benefit_details
  - check_partner_benefits
  - check_partner_dependant_details
  - check_partner_details
  - check_partner_employment
  - check_partner_employment_status
  - check_partner_housing_benefit
  - check_partner_housing_benefit_details
  - check_partner_income
  - check_partner_other_income
  - check_partner_outgoings
  - check_partner_property
  - check_partner_property_landlord
  - check_partner_property_entry
  - check_partner_vehicle
  - check_partner_vehicle_details
  - check_property
  - check_property_landlord
  - check_property_entry
  - check_regular_income
  - check_under_18_clr
  - check_under_eighteen_assets
  - check_vehicle
  - check_vehicle_details
  - check_vehicles_details
  - civil_legal_aid_eligibility_calculator
  - client_age
  - create_benefits
  - create_provider_users
  - cw_form_selection
  - dependant_details
  - dependant_income
  - dependant_income_details
  - document_lc_guidance_certificated
  - document_lc_guidance_certificated_assets_section
  - document_lc_guidance_controlled
  - document_lc_guidance_controlled_assets_section
  - document_lc_guidance_controlled_disregarded_payments_section
  - document_lc_guidance_controlled_over_60_section
  - document_lc_guidance_controlled_passporting_benefit_section
  - document_lc_guidance_controlled_properties_guidance_section
  - document_legislation_CLAR_2013
  - document_legislation_ammendments
  - document_mental_health_guidance
  - domestic_abuse_applicant
  - download_civ_means_7
  - download_civ_means_7_welsh
  - download_cw1
  - download_cw1_and_2
  - download_cw1_and_2_welsh
  - download_cw1_welsh
  - download_cw2
  - download_cw2_welsh
  - download_cw5
  - download_cw5_welsh
  - download_results
  - edit_benefits
  - employment
  - employment_status
  - end_of_journey
  - estimates_show
  - housing_benefit
  - housing_benefit_details
  - housing_costs
  - how_to_aggregate
  - immigration_or_asylum
  - immigration_or_asylum_type
  - immigration_or_asylum_type_upper_tribunal
  - income
  - index_start
  - index_updates
  - ineligible_gross_income
  - lc_guidance_certificated
  - lc_guidance_certificated/.
  - lc_guidance_controlled
  - legal_aid_checker_for_public
  - legislation_LASPO_2012_immigration
  - legislation_LASPO_2012_immigration/.
  - legislation_cla_2012
  - legislation_cla_2012/.
  - level_of_help
  - level_of_help_choice
  - matter_type
  - means_testing_guidance/.
  - mental_health_guidance
  - mental_health_guidance/.
  - mortgage_or_loan_payment
  - new_benefits
  - new_partner_benefits
  - other_income
  - outgoings
  - partner_additional_property
  - partner_additional_property_details
  - partner_assets
  - partner_benefit_details
  - partner_benefits
  - partner_dependant_details
  - partner_details
  - partner_employment
  - partner_employment_status
  - partner_housing_benefit
  - partner_housing_benefit_details
  - partner_income
  - partner_other_income
  - partner_outgoings
  - partner_property
  - partner_property_entry
  - partner_vehicle
  - partner_vehicle_details
  - print_results
  - property
  - property_entry
  - regular_income
  - results_show
  - show_accessibilities
  - show_cookies
  - show_helps
  - show_privacies
  - show_provider_users
  - show_referrals
  - start_index
  - under_18_clr
  - under_eighteen_assets
  - vehicle
  - vehicle_details
  - vehicles_details
  - view_results
  - old-calculator
