default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 25 } %>
  timeout: 5000

development:
  primary: &primary_development
    <<: *default
    database: ccq_development
  cache:
    <<: *primary_development
    database: ccq_development_cache
    migrations_paths:
      - db/cache_migrate

test:
  primary: &primary_test
    <<: *default
    database: ccq_test<%= ENV['TEST_ENV_NUMBER'] %>
  cache:
    <<: *primary_test
    database: ccq_test_cache<%= ENV['TEST_ENV_NUMBER'] %>
    migrations_paths:
      - db/cache_migrate

production:
  primary: &primary_production
    <<: *default
    host: <%= ENV['POSTGRES_HOST'] %>
    username: <%= ENV['POSTGRES_USER'] %>
    password: <%= ENV['POSTGRES_PASSWORD'] %>
    database: <%= ENV['POSTGRES_DATABASE'] %>
  cache:
    <<: *primary_production
    database: app_production_cache
    migrations_paths:
      - db/cache_migrate