default: &default
  adapter: "<%= ENV['CCQ_MODE'] == 'embedded' ? 'nulldb' : 'postgresql' %>"
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 25 } %>
  timeout: 5000

development:
  <<: *default
  database: ccq_development

test:
  <<: *default
  database: ccq_test<%= ENV['TEST_ENV_NUMBER'] %>

production:
  <<: *default
  host: <%= ENV['POSTGRES_HOST'] unless ENV['CCQ_MODE'] == 'embedded' %>
  username: <%= ENV['POSTGRES_USER'] unless ENV['CCQ_MODE'] == 'embedded' %>
  password: <%= ENV['POSTGRES_PASSWORD'] unless ENV['CCQ_MODE'] == 'embedded' %>
  database: <%= ENV['POSTGRES_DATABASE'] unless ENV['CCQ_MODE'] == 'embedded' %>