default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 25 } %>
  timeout: 5000

development:
  <<: *default
  database: ccq_development
  
test:
  <<: *default
  database: ccq_test
  host: <%= ENV['CODESPACES_POSTGRES_HOST'] %>
  username: <%= ENV['CODESPACES_POSTGRES_USER'] %>
  password: <%= ENV['CODESPACES_POSTGRES_PASSWORD'] %>

production:
  <<: *default
  host: <%= ENV['POSTGRES_HOST'] %>
  username: <%= ENV['POSTGRES_USER'] %>
  password: <%= ENV['POSTGRES_PASSWORD'] %>
  database: <%= ENV['POSTGRES_DATABASE'] %>
