require "rails_helper"

RSpec.describe CfeService do
  describe ".call", :controlled_flag do
    context "when there is a full set of data" do
      let(:session_data) do
        {
          "level_of_help" => "certificated",
          "proceeding_type" => nil,
          "legacy_proceeding_type" => "SE003",
          "over_60" => false,
          "employment_status" => "receiving_statutory_pay",
          "partner" => true,
          "passporting" => false,
          "child_dependants" => true,
          "child_dependants_count" => 2,
          "adult_dependants" => true,
          "adult_dependants_count" => 1,
          "frequency" => "two_weeks",
          "gross_income" => 123,
          "income_tax" => 1,
          "national_insurance" => 1,
          "housing_benefit" => true,
          "housing_benefit_value" => 234,
          "housing_benefit_frequency" => "every_week",
          "benefits" => [{ "id" => "c7b72db5-2c4d-4f04-a7c8-4b5adae1bfa0", "benefit_type" => "aaa", "benefit_amount" => 345, "benefit_frequency" => "monthly" }],
          "add_benefit" => false,
          "friends_or_family_value" => 45,
          "friends_or_family_frequency" => "every_week",
          "maintenance_value" => 56,
          "maintenance_frequency" => "every_two_weeks",
          "property_or_lodger_value" => 67,
          "property_or_lodger_frequency" => "every_four_weeks",
          "pension_value" => 78,
          "pension_frequency" => "monthly",
          "student_finance_value" => 89,
          "other_value" => 9,
          "housing_payments_value" => 12,
          "housing_payments_frequency" => "every_week",
          "childcare_payments_value" => 23,
          "childcare_payments_frequency" => "every_two_weeks",
          "maintenance_payments_value" => 34,
          "maintenance_payments_frequency" => "total",
          "legal_aid_payments_value" => 46,
          "legal_aid_payments_frequency" => "monthly",
          "property_owned" => "with_mortgage",
          "house_value" => 234_234,
          "mortgage" => 123_123,
          "percentage_owned" => 80,
          "house_in_dispute" => false,
          "joint_ownership" => true,
          "joint_percentage_owned" => 11,
          "vehicle_owned" => true,
          "vehicle_value" => 5556,
          "vehicle_pcp" => true,
          "vehicle_finance" => 4445,
          "vehicle_over_3_years_ago" => true,
          "vehicle_in_regular_use" => false,
          "vehicle_in_dispute" => true,
          "property_value" => 123,
          "property_mortgage" => 1313,
          "property_percentage_owned" => 44,
          "savings" => 553,
          "investments" => 345,
          "valuables" => 665,
          "in_dispute" => %w[savings investments valuables],
          "partner_over_60" => true,
          "partner_employment_status" => "in_work",
          "partner_child_dependants" => true,
          "partner_child_dependants_count" => 2,
          "partner_adult_dependants" => true,
          "partner_adult_dependants_count" => 5,
          "partner_frequency" => "week",
          "partner_gross_income" => 1414,
          "partner_income_tax" => 44,
          "partner_national_insurance" => 55,
          "partner_housing_benefit" => true,
          "partner_housing_benefit_value" => 2424,
          "partner_housing_benefit_frequency" => "every_week",
          "partner_benefits" => [{ "id" => "ae684d05-10d8-4c22-bc47-5dc7e9f109d3", "benefit_type" => "bbb", "benefit_amount" => 887, "benefit_frequency" => "every_two_weeks" }],
          "partner_add_benefit" => false,
          "partner_friends_or_family_value" => 99,
          "partner_friends_or_family_frequency" => "every_week",
          "partner_maintenance_value" => 89,
          "partner_maintenance_frequency" => "every_two_weeks",
          "partner_property_or_lodger_value" => 668,
          "partner_property_or_lodger_frequency" => "monthly",
          "partner_pension_value" => 464,
          "partner_pension_frequency" => "total",
          "partner_student_finance_value" => 776,
          "partner_other_value" => 335,
          "partner_housing_payments_value" => 86,
          "partner_housing_payments_frequency" => "every_four_weeks",
          "partner_childcare_payments_value" => 14,
          "partner_childcare_payments_frequency" => "every_two_weeks",
          "partner_maintenance_payments_value" => 87,
          "partner_maintenance_payments_frequency" => "monthly",
          "partner_legal_aid_payments_value" => 117,
          "partner_legal_aid_payments_frequency" => "every_week",
          "partner_vehicle_owned" => true,
          "partner_vehicle_value" => 887,
          "partner_vehicle_pcp" => true,
          "partner_vehicle_finance" => 355,
          "partner_vehicle_over_3_years_ago" => false,
          "partner_vehicle_in_regular_use" => true,
          "partner_property_value" => 11_266,
          "partner_property_mortgage" => 300,
          "partner_property_percentage_owned" => 44,
          "partner_savings" => 548,
          "partner_investments" => 997,
          "partner_valuables" => 234,
        }
      end
      let(:calculation_result) { CalculationResult.new({}) }
      let(:mock_connection) { instance_double(CfeConnection) }
      let(:arbitrary_fixed_time) { Date.new(2023, 3, 8) }
      let(:assessment_id) { "assessment-id" }

      before do
        travel_to arbitrary_fixed_time
        allow(CfeConnection).to receive(:connection).and_return(mock_connection)
      end

      it "sends all required information to CFE and returns the result" do
        allow(mock_connection).to receive(:create_assessment_id).with(
          { level_of_representation: "certificated", submission_date: arbitrary_fixed_time },
        ).and_return(assessment_id)

        expect(mock_connection).to receive(:create_dependants).with(
          assessment_id,
          [{ assets_value: 0,
             date_of_birth: 11.years.ago.to_date,
             in_full_time_education: true,
             monthly_income: 0,
             relationship: "child_relative" },
           { assets_value: 0,
             date_of_birth: 11.years.ago.to_date,
             in_full_time_education: true,
             monthly_income: 0,
             relationship: "child_relative" },
           { assets_value: 0,
             date_of_birth: 21.years.ago.to_date,
             in_full_time_education: false,
             monthly_income: 0,
             relationship: "adult_relative" }],
        )

        expect(mock_connection).to receive(:create_proceeding_types).with(
          assessment_id,
          [{ ccms_code: "SE003", client_involvement_type: "A" }],
        )

        expect(mock_connection).to receive(:create_employments).with(
          assessment_id,
          [{ client_id: "ID",
             name: "Job",
             payments: [{ benefits_in_kind: 0,
                          client_id: "id-0",
                          date: Date.current,
                          gross: 123,
                          national_insurance: -1,
                          net_employment_income: 121,
                          tax: -1 },
                        { benefits_in_kind: 0,
                          client_id: "id-1",
                          date: 2.weeks.ago,
                          gross: 123,
                          national_insurance: -1,
                          net_employment_income: 121,
                          tax: -1 },
                        { benefits_in_kind: 0,
                          client_id: "id-2",
                          date: 4.weeks.ago,
                          gross: 123,
                          national_insurance: -1,
                          net_employment_income: 121,
                          tax: -1 },
                        { benefits_in_kind: 0,
                          client_id: "id-3",
                          date: 6.weeks.ago,
                          gross: 123,
                          national_insurance: -1,
                          net_employment_income: 121,
                          tax: -1 },
                        { benefits_in_kind: 0,
                          client_id: "id-4",
                          date: 8.weeks.ago,
                          gross: 123,
                          national_insurance: -1,
                          net_employment_income: 121,
                          tax: -1 },
                        { benefits_in_kind: 0,
                          client_id: "id-5",
                          date: 10.weeks.ago,
                          gross: 123,
                          national_insurance: -1,
                          net_employment_income: 121,
                          tax: -1 }],
             receiving_only_statutory_sick_or_maternity_pay: true }],
        )

        expect(mock_connection).to receive(:create_state_benefits).with(
          assessment_id,
          [{ name: "aaa",
             payments: [{ amount: 345, client_id: "", date: Date.current },
                        { amount: 345, client_id: "", date: 1.month.ago },
                        { amount: 345, client_id: "", date: 2.months.ago }] },
           { name: "housing_benefit",
             payments: [{ amount: 234, client_id: "", date: Date.current },
                        { amount: 234, client_id: "", date: 1.week.ago },
                        { amount: 234, client_id: "", date: 2.weeks.ago },
                        { amount: 234, client_id: "", date: 3.weeks.ago },
                        { amount: 234, client_id: "", date: 4.weeks.ago },
                        { amount: 234, client_id: "", date: 5.weeks.ago },
                        { amount: 234, client_id: "", date: 6.weeks.ago },
                        { amount: 234, client_id: "", date: 7.weeks.ago },
                        { amount: 234, client_id: "", date: 8.weeks.ago },
                        { amount: 234, client_id: "", date: 9.weeks.ago },
                        { amount: 234, client_id: "", date: 10.weeks.ago },
                        { amount: 234, client_id: "", date: 11.weeks.ago }] }],
        )

        expect(mock_connection).to receive(:create_irregular_incomes).with(
          assessment_id,
          [{ amount: 89, frequency: "annual", income_type: "student_loan" },
           { amount: 9,
             frequency: "quarterly",
             income_type: "unspecified_source" }],
        )

        expect(mock_connection).to receive(:create_vehicles).with(
          assessment_id,
          [{ date_of_purchase: 4.years.ago,
             in_regular_use: false,
             loan_amount_outstanding: 4445,
             subject_matter_of_dispute: true,
             value: 5556 }],
        )

        expect(mock_connection).to receive(:create_capitals).with(
          assessment_id,
          { bank_accounts: [{ description: "Liquid Asset",
                              subject_matter_of_dispute: true,
                              value: 553 }],
            non_liquid_capital: [{ description: "Non Liquid Asset",
                                   subject_matter_of_dispute: true,
                                   value: 345 },
                                 { description: "Non Liquid Asset",
                                   subject_matter_of_dispute: true,
                                   value: 665 }] },
        )

        expect(mock_connection).to receive(:create_properties).with(
          assessment_id,
          { additional_properties: [{ outstanding_mortgage: 1313,
                                      percentage_owned: 44,
                                      shared_with_housing_assoc: false,
                                      value: 123 }],
            main_home: { outstanding_mortgage: 123_123,
                         percentage_owned: 91,
                         shared_with_housing_assoc: false,
                         value: 234_234 } },
        )

        expect(mock_connection).to receive(:create_regular_transactions).with(
          assessment_id,
          [{ amount: 45,
             category: :friends_or_family,
             frequency: :weekly,
             operation: :credit },
           { amount: 56,
             category: :maintenance_in,
             frequency: :two_weekly,
             operation: :credit },
           { amount: 67,
             category: :property_or_lodger,
             frequency: :four_weekly,
             operation: :credit },
           { amount: 78,
             category: :pension,
             frequency: :monthly,
             operation: :credit },
           { amount: 12,
             category: :rent_or_mortgage,
             frequency: :weekly,
             operation: :debit },
           { amount: 23,
             category: :child_care,
             frequency: :two_weekly,
             operation: :debit },
           { amount: 34,
             category: :maintenance_out,
             frequency: :three_monthly,
             operation: :debit },
           { amount: 46,
             category: :legal_aid,
             frequency: :monthly,
             operation: :debit }],
        )

        expect(mock_connection).to receive(:create_applicant).with(
          assessment_id,
          { date_of_birth: 50.years.ago,
            employed: true,
            has_partner_opponent: false,
            receives_qualifying_benefit: false },
        )

        expect(mock_connection).to receive(:create_partner_financials).with(
          assessment_id,
          { additional_properties: [{ outstanding_mortgage: 300,
                                      percentage_owned: 44,
                                      shared_with_housing_assoc: false,
                                      value: 11_266.to_d }],
            capitals: { bank_accounts: [{ description: "Liquid Asset",
                                          subject_matter_of_dispute: false,
                                          value: 548.to_d }],
                        non_liquid_capital: [{ description: "Non Liquid Asset",
                                               subject_matter_of_dispute: false,
                                               value: 997.to_d },
                                             { description: "Non Liquid Asset",
                                               subject_matter_of_dispute: false,
                                               value: 234.to_d }] },
            dependants: [{ assets_value: 0,
                           date_of_birth: 11.years.ago.to_date,
                           in_full_time_education: true,
                           monthly_income: 0,
                           relationship: "child_relative" },
                         { assets_value: 0,
                           date_of_birth: 11.years.ago.to_date,
                           in_full_time_education: true,
                           monthly_income: 0,
                           relationship: "child_relative" },
                         { assets_value: 0,
                           date_of_birth: 21.years.ago.to_date,
                           in_full_time_education: false,
                           monthly_income: 0,
                           relationship: "adult_relative" },
                         { assets_value: 0,
                           date_of_birth: 21.years.ago.to_date,
                           in_full_time_education: false,
                           monthly_income: 0,
                           relationship: "adult_relative" },
                         { assets_value: 0,
                           date_of_birth: 21.years.ago.to_date,
                           in_full_time_education: false,
                           monthly_income: 0,
                           relationship: "adult_relative" },
                         { assets_value: 0,
                           date_of_birth: 21.years.ago.to_date,
                           in_full_time_education: false,
                           monthly_income: 0,
                           relationship: "adult_relative" },
                         { assets_value: 0,
                           date_of_birth: 21.years.ago.to_date,
                           in_full_time_education: false,
                           monthly_income: 0,
                           relationship: "adult_relative" }],
            employments: [{ client_id: "ID",
                            name: "Job",
                            payments: [{ benefits_in_kind: 0,
                                         client_id: "id-0",
                                         date: Date.current.to_date,
                                         gross: 1414,
                                         national_insurance: -55,
                                         net_employment_income: 1315,
                                         tax: -44.to_d },
                                       { benefits_in_kind: 0,
                                         client_id: "id-1",
                                         date: 1.week.ago.to_date,
                                         gross: 1414,
                                         national_insurance: -55,
                                         net_employment_income: 1315,
                                         tax: -44.to_d },
                                       { benefits_in_kind: 0,
                                         client_id: "id-2",
                                         date: 2.weeks.ago.to_date,
                                         gross: 1414,
                                         national_insurance: -55,
                                         net_employment_income: 1315,
                                         tax: -44.to_d },
                                       { benefits_in_kind: 0,
                                         client_id: "id-3",
                                         date: 3.weeks.ago.to_date,
                                         gross: 1414,
                                         national_insurance: -55,
                                         net_employment_income: 1315,
                                         tax: -44.to_d },
                                       { benefits_in_kind: 0,
                                         client_id: "id-4",
                                         date: 4.weeks.ago.to_date,
                                         gross: 1414,
                                         national_insurance: -55,
                                         net_employment_income: 1315,
                                         tax: -44.to_d },
                                       { benefits_in_kind: 0,
                                         client_id: "id-5",
                                         date: 5.weeks.ago.to_date,
                                         gross: 1414,
                                         national_insurance: -55,
                                         net_employment_income: 1315,
                                         tax: -44.to_d },
                                       { benefits_in_kind: 0,
                                         client_id: "id-6",
                                         date: 6.weeks.ago.to_date,
                                         gross: 1414,
                                         national_insurance: -55,
                                         net_employment_income: 1315,
                                         tax: -44.to_d },
                                       { benefits_in_kind: 0,
                                         client_id: "id-7",
                                         date: 7.weeks.ago.to_date,
                                         gross: 1414,
                                         national_insurance: -55,
                                         net_employment_income: 1315,
                                         tax: -44.to_d },
                                       { benefits_in_kind: 0,
                                         client_id: "id-8",
                                         date: 8.weeks.ago.to_date,
                                         gross: 1414,
                                         national_insurance: -55,
                                         net_employment_income: 1315,
                                         tax: -44.to_d },
                                       { benefits_in_kind: 0,
                                         client_id: "id-9",
                                         date: 9.weeks.ago.to_date,
                                         gross: 1414,
                                         national_insurance: -55,
                                         net_employment_income: 1315,
                                         tax: -44.to_d },
                                       { benefits_in_kind: 0,
                                         client_id: "id-10",
                                         date: 10.weeks.ago.to_date,
                                         gross: 1414,
                                         national_insurance: -55,
                                         net_employment_income: 1315,
                                         tax: -44.to_d },
                                       { benefits_in_kind: 0,
                                         client_id: "id-11",
                                         date: 11.weeks.ago.to_date,
                                         gross: 1414,
                                         national_insurance: -55,
                                         net_employment_income: 1315,
                                         tax: -44.to_d }],
                            receiving_only_statutory_sick_or_maternity_pay: false }],
            irregular_incomes: [{ amount: 776, frequency: "annual", income_type: "student_loan" },
                                { amount: 335,
                                  frequency: "quarterly",
                                  income_type: "unspecified_source" }],
            partner: { date_of_birth: 70.years.ago.to_date, employed: true },
            regular_transactions: [{ amount: 99,
                                     category: :friends_or_family,
                                     frequency: :weekly,
                                     operation: :credit },
                                   { amount: 89,
                                     category: :maintenance_in,
                                     frequency: :two_weekly,
                                     operation: :credit },
                                   { amount: 668,
                                     category: :property_or_lodger,
                                     frequency: :monthly,
                                     operation: :credit },
                                   { amount: 464,
                                     category: :pension,
                                     frequency: :three_monthly,
                                     operation: :credit },
                                   { amount: 86,
                                     category: :rent_or_mortgage,
                                     frequency: :four_weekly,
                                     operation: :debit },
                                   { amount: 14,
                                     category: :child_care,
                                     frequency: :two_weekly,
                                     operation: :debit },
                                   { amount: 87,
                                     category: :maintenance_out,
                                     frequency: :monthly,
                                     operation: :debit },
                                   { amount: 117,
                                     category: :legal_aid,
                                     frequency: :weekly,
                                     operation: :debit }],
            state_benefits: [{ name: "bbb",
                               payments: [{ amount: 887, client_id: "", date: Date.current.to_date },
                                          { amount: 887, client_id: "", date: 2.weeks.ago.to_date },
                                          { amount: 887, client_id: "", date: 4.weeks.ago.to_date },
                                          { amount: 887, client_id: "", date: 6.weeks.ago.to_date },
                                          { amount: 887, client_id: "", date: 8.weeks.ago.to_date },
                                          { amount: 887, client_id: "", date: 10.weeks.ago.to_date }] },
                             { name: "housing_benefit",
                               payments: [{ amount: 2424, client_id: "", date: Date.current.to_date },
                                          { amount: 2424, client_id: "", date: 1.week.ago.to_date },
                                          { amount: 2424, client_id: "", date: 2.weeks.ago.to_date },
                                          { amount: 2424, client_id: "", date: 3.weeks.ago.to_date },
                                          { amount: 2424, client_id: "", date: 4.weeks.ago.to_date },
                                          { amount: 2424, client_id: "", date: 5.weeks.ago.to_date },
                                          { amount: 2424, client_id: "", date: 6.weeks.ago.to_date },
                                          { amount: 2424, client_id: "", date: 7.weeks.ago.to_date },
                                          { amount: 2424, client_id: "", date: 8.weeks.ago.to_date },
                                          { amount: 2424, client_id: "", date: 9.weeks.ago.to_date },
                                          { amount: 2424, client_id: "", date: 10.weeks.ago.to_date },
                                          { amount: 2424, client_id: "", date: 11.weeks.ago.to_date }] }],
            vehicles: [{ date_of_purchase: 2.years.ago.to_date,
                         in_regular_use: true,
                         loan_amount_outstanding: 355,
                         subject_matter_of_dispute: false,
                         value: 887.to_d }] },
        )

        allow(mock_connection).to receive(:api_result).with(assessment_id).and_return(calculation_result)

        result = described_class.call(session_data)
        expect(result).to eq calculation_result
        expect(calculation_result.level_of_help).to eq "certificated"
      end
    end
  end

  describe ".create_assessment_id" do
    let(:mock_connection) { instance_double(CfeConnection) }
    let(:session_data) { {} }

    it "does not include level of help in payload if none is specified" do
      expect(mock_connection).to receive(:create_assessment_id).with({ submission_date: Date.current })
      described_class.create_assessment_id(mock_connection, session_data)
    end
  end
end
