apiVersion: v1
appVersion: "1.1"
description: A Helm chart for Kubernetes
name: laa-estimate-eligibility
version: 0.3.0
dependencies:
  - name: postgresql
    version: ^16.6.0
    condition: postgresql.enabled
    repository: https://charts.bitnami.com/bitnami
