# we use the same nginx config template both for docker compose and 
# in deployed environments - these maps make sure nginx always gets
# the correct value.
#
# in docker-compose, the X- headers won't exist, but in EKS, they are
# passed in from the cluster ingress (ingress-nginx).
#
# $http_ variables are created by nginx for every header it receives.


# capture incoming protocol (http/https) - used in proxy.conf
# sets $proxy_x_forwarded_proto to $http_x_forwarded_proto if exists, else $scheme
map $http_x_forwarded_proto $proxy_x_forwarded_proto {
    default $http_x_forwarded_proto;
    ''      $scheme;
}

# capture incoming port - used in proxy.conf
# sets $proxy_x_forwarded_port to $http_x_forwarded_port if exists, else $server_port
map $http_x_forwarded_port $proxy_x_forwarded_port {
    default $http_x_forwarded_port;
    ''      $server_port;
}

# preserve incoming Host header (including optional port), with a safe fallback
map $http_host $proxy_host {
    default $http_host;
    ''      $host;
}