name: "Generate browsertools docker image"
on:
  push:
    branches:
      - main
      - puppeteer-*
    paths:
      - Dockerfile_browser_tools.dockerfile
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build-push:
    uses: ./.github/workflows/browser-tools-docker-image-reusable.yml
    with:
      source_ref: ${{ github.ref_name }}
      image_tag: ${{ github.ref_name }}
      source_actor: ${{ github.actor }}
      enforce_actor_policy: true
    secrets: inherit
