name: "Generate browsertools docker image"
on:
  push:
    branches:
      - main
      - puppeteer-2440

jobs:
  build-push:
    runs-on: ubuntu-latest
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@4907a6ddec9925e35a0a9e82d7399ccc52663121 # v4.1.0
        with:
          username: ${{ secrets.DOCKERHUB_USER_CCQ }}
          password: ${{ secrets.DOCKERHUB_PAT_CCQ }}
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - name: Build the Docker image
        run: |
          docker build -f ./Dockerfile_browser_tools.dockerfile . -t checkclientqualifiesdocker/circleci-image:${{ github.ref_name }}
      - name: Push the Docker image
        run: |
          docker push checkclientqualifiesdocker/circleci-image:${{ github.ref_name }}
