name: Raise Dependabot Jira Issue

on:
  pull_request:
    types: [opened]

jobs:
  gajira:
    name: Raise Jira Issue
    runs-on: ubuntu-latest
    if: ${{ contains(github.event.pull_request.labels.*.name, 'dependencies') }}

    steps:
    - name: Login
      uses: atlassian/gajira-login@master
      env:
        JIRA_BASE_URL: ${{ secrets.JIRA_BASE_URL }}
        JIRA_USER_EMAIL: ${{ secrets.JIRA_USER_EMAIL }}
        JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}

    - name: Create Jira ticket
      id: create
      uses: atlassian/gajira-create@master
      with:
          project: EL
          issuetype: Task
          summary: |
            Dependabot: ${{ github.event.pull_request.title }}, GitHub PR#${{github.event.number}}  
          description: |
            ${{ github.event.pull_request.body }}
            Repo link: https://github.com/${{ github.repository }}
            In addition, please resolve other issues, if any. 
