name: RCW build

on:
  workflow_dispatch: # Allows manual triggering of the workflow

jobs:
  build-image:
    name: Build Docker Image
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6

      - name: Set up AWS credentials for ECR and Kubernetes
        uses: aws-actions/configure-aws-credentials@8df5847569e6427dd6c4fb1cf565c83acfa8afa7 # v6.0.0
        with:
          role-to-assume: ${{ secrets.CCQ_ECR_ROLE_TO_ASSUME }}
          aws-region: ${{ vars.CCQ_ECR_REGION }}

      - uses: aws-actions/amazon-ecr-login@fe725d47d3009d901b44f3df285a6dc9d438e63a
        id: login-ecr

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@c8ad1c5d0f6f39c2bc446b807fa8ea2afadcddb6

      - name: Cache Docker layers
        uses: actions/cache@cdf6c1fa76f9f475f3d7449005a359c84ca0f306 # v5
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Build and push image with local action
        uses: ./.github/actions/build_and_push
        with:
          image_registry: ${{ secrets.ECR_REGISTRY_URL }}
          image_repo: ${{ vars.CCQ_ECR_REPOSITORY }}
          dockerfile_path: Dockerfile
          image_tag: ${{ github.sha }}
