name: RuboCop

on: [pull_request]

permissions:
  contents: read

jobs:
  rubocop:
    runs-on: ubuntu-latest
    env:
      BUNDLE_ONLY: test

    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Set up Ruby
        uses: ruby/setup-ruby@95ef2b042f9d7a56d8268cba8559e2842e2ad01b # v1.321.0
        with:
          ruby-version: 4.0.5
          bundler-cache: true

      - name: Run RuboCop
        run: bundle exec rubocop
